version: '3.8'


services:
    database-books:
        image: mysql
        container_name: database-books
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: 1234
        ports:
            - '1234:3306'
    php-apache-books:
        container_name: php-apache-books
        build:
            context: .
        ports:
            - '8085:80'
        volumes:
            - .:/var/www/laravel_docker
            - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
        depends_on:
            - database-books
