<?php

namespace Tests\Integration\BookManage;

use App\Models\Book;
use App\Models\User;
use Faker\Factory;
use Illuminate\Support\Facades\DB;
use function bcrypt;
use function route;

class CreateTest extends \Tests\TestCase
{
    private $faker;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->faker = Factory::create();
        //DB::beginTransaction();

    }

    /**
     * Test, that users without admin rights cannot create book
     * @return void
     */
    public function testAdminAccess()
    {
        $user = new User
        (
            [
                'name' => $this->faker->name,
                'email' => $this->faker->email,
                'password' => bcrypt($this->faker->password),
                'isAdmin' => false
            ]
        );

        $user->save();
        auth()->login($user);
        $this->post(route('manageBook.store'), [])->assertStatus(403);
    }



    public function tearDown(): void
    {
       // DB::rollBack();
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

}
