<?php

namespace Tests\Integration\Auth;

use Faker\Factory;
use Illuminate\Support\Facades\DB;

class DBAuthTest extends \Tests\TestCase
{

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->faker = Factory::create();
        DB::beginTransaction();

    }


    public function tearDown(): void
    {
        DB::rollBack();

        parent::tearDown(); // TODO: Change the autogenerated stub
    }

}
