<?php

namespace Tests\Integration\Auth;

use App\Http\Middleware\VerifyCsrfToken;
use Faker\Factory;
use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Support\Facades\DB;

class DBAuthTest extends \Tests\TestCase
{
    use WithoutMiddleware;

    public \Faker\Generator $faker;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->faker = Factory::create();
        DB::beginTransaction();

    }




    protected function tearDown(): void
    {
        DB::rollBack();

        parent::tearDown(); // TODO: Change the autogenerated stub
    }

}
