<?php

namespace Tests\Integration\Search;

use App\Models\Book;
use App\Models\Genre;
use Core\Constants;
use Faker\Factory;
use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Lang;

class AuthorsTest extends \Tests\TestCase implements Constants
{
    use WithoutMiddleware;

    private $faker;
    private Genre $genre;
    private Book $book;
    private const TEST_NAME = "TEST_NAME";


    /**
     * @return void
     */
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->faker = Factory::create();
        DB::beginTransaction();

        $this->genre = new Genre(['name' => $this->faker->name]);
        $this->genre->save();
        $this->book = new Book
        (
            [
                'name' => $this->faker->name,
                'annotation' => $this->faker->name,
                'authors' => self::TEST_NAME,
                'price' => 0,
                'isHidden' => false,
                'genreId' => $this->genre->getId()
            ]
        );

        $this->book->save();
    }


    /**
     * Test books with names, that contains string of searching name
     * @dataProvider dataProvider
     * @return void
     */
    public function test_similar_books_correct(array $data)
    {
        $data['genreId'] = $this->genre->getId();
        $book = new Book($data);
        $book->save();
        $books = $this->book->searchByAuthors($this->book->authors);
        $this->assertEquals($books[0]->getName(), $book->getName());
    }

    public function dataProvider()
    {
        $faker = Factory::create();
        return
            [
                'substr_in_begin' =>
                    [
                        [
                            'name' => $faker->name,
                            'annotation' => $faker->name,
                            'authors' => self::TEST_NAME . $faker->name,
                            'price' => 0,
                            'isHidden' => false,
                            'genreId' => 0
                        ]
                    ],

                'substr_in_middle' =>
                    [
                        [
                            'name' => $faker->name,
                            'annotation' => $faker->name,
                            'authors' => $faker->name.self::TEST_NAME . $faker->name,
                            'price' => 0,
                            'isHidden' => false,
                            'genreId' => 0
                        ]
                    ],

                'substr_in_end' =>
                    [
                        [
                            'name' => $faker->name,
                            'annotation' => $faker->name,
                            'authors' => $faker->name.self::TEST_NAME,
                            'price' => 0,
                            'isHidden' => false,
                            'genreId' => 0
                        ]
                    ],

                'substr_lower_case' =>
                    [
                        [
                            'name' => $faker->name,
                            'annotation' => $faker->name,
                            'authors' => $faker->name.self::TEST_NAME,
                            'price' => 0,
                            'isHidden' => false,
                            'genreId' => 0
                        ]
                    ]
            ];
    }


    /**
     * Test books with names, that not contains string of searching name
     * @dataProvider dataProviderIncorrect
     * @return void
     */
    public function test_similar_books_incorrect(array $data)
    {
        $data['genreId'] = $this->genre->getId();
        $book = new Book($data);
        $book->save();

        $books = $this->book->searchByAuthors($this->book->authors);
        $this->assertEmpty($books->toArray());
    }

    public function dataProviderIncorrect()
    {
        $faker = Factory::create();
        return
            [
                'incorrect_substr' =>
                    [
                        [
                            'name' => $faker->name,
                            'annotation' => $faker->name,
                            'authors' => $faker->name,
                            'price' => 0,
                            'isHidden' => false,
                            'genreId' => 0
                        ]
                    ],

            ];
    }


    /**
     * @return void
     */
    public function tearDown(): void
    {
        DB::rollBack();
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

}
