<?php

namespace Tests\Unit;

use App\Http\Controllers\ManageBooksController;
use App\Http\Requests\CreateBookRequest;
use App\Models\Book;
use App\Models\User;
use Tests\TestCase;


class ExampleTest extends TestCase
{

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function test_example()
    {
        $controller = new ManageBooksController();
        $bookrequest = new CreateBookRequest();
        $bookrequest->merge(['name'=>'15','annotation'=>'a','authors'=>'aa','price'=>12,'genreId'=>75]);

        dd($controller->store($bookrequest));
    }
}
